# TCL File Generated by Component Editor 16.1
# Sat Apr 07 18:20:43 MSK 2018
# DO NOT MODIFY


# 
# bloom_filter "Bloom Filter IP-core" v1.0
# mt 2018.04.07.18:20:43
# IP-core of Bloom filter on internal memory with various parameters
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bloom_filter
# 
set_module_property DESCRIPTION "IP-core of Bloom filter on internal memory with various parameters"
set_module_property NAME bloom_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Algorithms
set_module_property AUTHOR mt
set_module_property DISPLAY_NAME "Bloom Filter IP-core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bloom_filter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file amm_writer.sv SYSTEM_VERILOG PATH ../rtl/amm_writer.sv
add_fileset_file ast_shift.sv SYSTEM_VERILOG PATH ../rtl/ast_shift.sv
add_fileset_file bloom_filter.sv SYSTEM_VERILOG PATH ../rtl/bloom_filter.sv TOP_LEVEL_FILE
add_fileset_file bloom_filter_csr.sv SYSTEM_VERILOG PATH ../rtl/bloom_filter_csr.sv
add_fileset_file bloom_filter_regs_pkg.sv SYSTEM_VERILOG PATH ../rtl/bloom_filter_regs_pkg.sv
add_fileset_file bloom_search_engine.sv SYSTEM_VERILOG PATH ../rtl/bloom_search_engine.sv
add_fileset_file crc.sv SYSTEM_VERILOG PATH ../rtl/crc.sv
add_fileset_file crc_pkg.sv SYSTEM_VERILOG PATH ../rtl/crc_pkg.sv
add_fileset_file data_dc_fifo.qip OTHER PATH ../rtl/data_dc_fifo.qip
add_fileset_file data_dc_fifo.sv SYSTEM_VERILOG PATH ../rtl/data_dc_fifo.sv
add_fileset_file data_delay.sv SYSTEM_VERILOG PATH ../rtl/data_delay.sv
add_fileset_file data_delay_pipeline_ready.sv SYSTEM_VERILOG PATH ../rtl/data_delay_pipeline_ready.sv
add_fileset_file data_to_ast.sv SYSTEM_VERILOG PATH ../rtl/data_to_ast.sv
add_fileset_file hash_lut.sv SYSTEM_VERILOG PATH ../rtl/hash_lut.sv
add_fileset_file hasher.sv SYSTEM_VERILOG PATH ../rtl/hasher.sv
add_fileset_file one_hot_arb.sv SYSTEM_VERILOG PATH ../rtl/one_hot_arb.sv
add_fileset_file one_hot_ast_mux.sv SYSTEM_VERILOG PATH ../rtl/one_hot_ast_mux.sv
add_fileset_file one_str_size_bloom_engine.sv SYSTEM_VERILOG PATH ../rtl/one_str_size_bloom_engine.sv
add_fileset_file strings_mux.sv SYSTEM_VERILOG PATH ../rtl/strings_mux.sv
add_fileset_file true_dp_ram.sv SYSTEM_VERILOG PATH ../rtl/true_dp_ram.sv


# 
# documentation links
# 
add_documentation_link "GitHub page" https://github.com/m1a1x1/bloom-filter


# 
# parameters
# 
add_parameter AST_SINK_SYMBOLS INTEGER 8 ""
set_parameter_property AST_SINK_SYMBOLS DEFAULT_VALUE 8
set_parameter_property AST_SINK_SYMBOLS DISPLAY_NAME AST_SINK_SYMBOLS
set_parameter_property AST_SINK_SYMBOLS WIDTH ""
set_parameter_property AST_SINK_SYMBOLS TYPE INTEGER
set_parameter_property AST_SINK_SYMBOLS UNITS None
set_parameter_property AST_SINK_SYMBOLS ALLOWED_RANGES 1:128
set_parameter_property AST_SINK_SYMBOLS DESCRIPTION "Avalon-ST Sink symbols per beat"
set_parameter_property AST_SINK_SYMBOLS HDL_PARAMETER true
add_parameter AST_SINK_ORDER BOOLEAN true ""
set_parameter_property AST_SINK_ORDER DEFAULT_VALUE true
set_parameter_property AST_SINK_ORDER DISPLAY_NAME AST_SINK_ORDER
set_parameter_property AST_SINK_ORDER WIDTH ""
set_parameter_property AST_SINK_ORDER TYPE BOOLEAN
set_parameter_property AST_SINK_ORDER UNITS None
set_parameter_property AST_SINK_ORDER DESCRIPTION "Avalon-ST Sink symbols order"
set_parameter_property AST_SINK_ORDER HDL_PARAMETER true
add_parameter AST_SOURCE_SYMBOLS INTEGER 2 ""
set_parameter_property AST_SOURCE_SYMBOLS DEFAULT_VALUE 2
set_parameter_property AST_SOURCE_SYMBOLS DISPLAY_NAME AST_SOURCE_SYMBOLS
set_parameter_property AST_SOURCE_SYMBOLS WIDTH ""
set_parameter_property AST_SOURCE_SYMBOLS TYPE INTEGER
set_parameter_property AST_SOURCE_SYMBOLS UNITS None
set_parameter_property AST_SOURCE_SYMBOLS ALLOWED_RANGES 1:128
set_parameter_property AST_SOURCE_SYMBOLS DESCRIPTION "Avalon-ST Source symbols per beat"
set_parameter_property AST_SOURCE_SYMBOLS HDL_PARAMETER true
add_parameter AST_SOURCE_ORDER BOOLEAN true ""
set_parameter_property AST_SOURCE_ORDER DEFAULT_VALUE true
set_parameter_property AST_SOURCE_ORDER DISPLAY_NAME AST_SOURCE_ORDER
set_parameter_property AST_SOURCE_ORDER WIDTH ""
set_parameter_property AST_SOURCE_ORDER TYPE BOOLEAN
set_parameter_property AST_SOURCE_ORDER UNITS None
set_parameter_property AST_SOURCE_ORDER DESCRIPTION "Avalon-ST Source symbols order"
set_parameter_property AST_SOURCE_ORDER HDL_PARAMETER true
add_parameter AMM_CSR_DATA_W INTEGER 16 ""
set_parameter_property AMM_CSR_DATA_W DEFAULT_VALUE 16
set_parameter_property AMM_CSR_DATA_W DISPLAY_NAME AMM_CSR_DATA_W
set_parameter_property AMM_CSR_DATA_W WIDTH ""
set_parameter_property AMM_CSR_DATA_W TYPE INTEGER
set_parameter_property AMM_CSR_DATA_W UNITS None
set_parameter_property AMM_CSR_DATA_W ALLOWED_RANGES 1:32
set_parameter_property AMM_CSR_DATA_W DESCRIPTION ""
set_parameter_property AMM_CSR_DATA_W HDL_PARAMETER true
add_parameter AMM_CSR_ADDR_W INTEGER 12 ""
set_parameter_property AMM_CSR_ADDR_W DEFAULT_VALUE 12
set_parameter_property AMM_CSR_ADDR_W DISPLAY_NAME AMM_CSR_ADDR_W
set_parameter_property AMM_CSR_ADDR_W WIDTH ""
set_parameter_property AMM_CSR_ADDR_W TYPE INTEGER
set_parameter_property AMM_CSR_ADDR_W UNITS None
set_parameter_property AMM_CSR_ADDR_W ALLOWED_RANGES 1:32
set_parameter_property AMM_CSR_ADDR_W DESCRIPTION ""
set_parameter_property AMM_CSR_ADDR_W HDL_PARAMETER true
add_parameter AMM_LUT_ADDR_W INTEGER 18 ""
set_parameter_property AMM_LUT_ADDR_W DEFAULT_VALUE 18
set_parameter_property AMM_LUT_ADDR_W DISPLAY_NAME AMM_LUT_ADDR_W
set_parameter_property AMM_LUT_ADDR_W WIDTH ""
set_parameter_property AMM_LUT_ADDR_W TYPE INTEGER
set_parameter_property AMM_LUT_ADDR_W UNITS None
set_parameter_property AMM_LUT_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_LUT_ADDR_W DESCRIPTION ""
set_parameter_property AMM_LUT_ADDR_W HDL_PARAMETER true
add_parameter AMM_LUT_DATA_W INTEGER 8 ""
set_parameter_property AMM_LUT_DATA_W DEFAULT_VALUE 8
set_parameter_property AMM_LUT_DATA_W DISPLAY_NAME AMM_LUT_DATA_W
set_parameter_property AMM_LUT_DATA_W WIDTH ""
set_parameter_property AMM_LUT_DATA_W TYPE INTEGER
set_parameter_property AMM_LUT_DATA_W ENABLED false
set_parameter_property AMM_LUT_DATA_W UNITS None
set_parameter_property AMM_LUT_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_LUT_DATA_W DESCRIPTION ""
set_parameter_property AMM_LUT_DATA_W HDL_PARAMETER true
add_parameter MIN_STR_SIZE INTEGER 3 ""
set_parameter_property MIN_STR_SIZE DEFAULT_VALUE 3
set_parameter_property MIN_STR_SIZE DISPLAY_NAME MIN_STR_SIZE
set_parameter_property MIN_STR_SIZE WIDTH ""
set_parameter_property MIN_STR_SIZE TYPE INTEGER
set_parameter_property MIN_STR_SIZE UNITS None
set_parameter_property MIN_STR_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MIN_STR_SIZE DESCRIPTION ""
set_parameter_property MIN_STR_SIZE HDL_PARAMETER true
add_parameter MAX_STR_SIZE INTEGER 5 ""
set_parameter_property MAX_STR_SIZE DEFAULT_VALUE 5
set_parameter_property MAX_STR_SIZE DISPLAY_NAME MAX_STR_SIZE
set_parameter_property MAX_STR_SIZE WIDTH ""
set_parameter_property MAX_STR_SIZE TYPE INTEGER
set_parameter_property MAX_STR_SIZE UNITS None
set_parameter_property MAX_STR_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_STR_SIZE DESCRIPTION ""
set_parameter_property MAX_STR_SIZE HDL_PARAMETER true
add_parameter HASHES_CNT INTEGER 6 ""
set_parameter_property HASHES_CNT DEFAULT_VALUE 6
set_parameter_property HASHES_CNT DISPLAY_NAME HASHES_CNT
set_parameter_property HASHES_CNT WIDTH ""
set_parameter_property HASHES_CNT TYPE INTEGER
set_parameter_property HASHES_CNT UNITS None
set_parameter_property HASHES_CNT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HASHES_CNT DESCRIPTION ""
set_parameter_property HASHES_CNT HDL_PARAMETER true
add_parameter HASH_W INTEGER 10 ""
set_parameter_property HASH_W DEFAULT_VALUE 10
set_parameter_property HASH_W DISPLAY_NAME HASH_W
set_parameter_property HASH_W WIDTH ""
set_parameter_property HASH_W TYPE INTEGER
set_parameter_property HASH_W UNITS None
set_parameter_property HASH_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HASH_W DESCRIPTION ""
set_parameter_property HASH_W HDL_PARAMETER true
add_parameter HASH_LUT_MODE INTEGER 1 ""
set_parameter_property HASH_LUT_MODE DEFAULT_VALUE 1
set_parameter_property HASH_LUT_MODE DISPLAY_NAME HASH_LUT_MODE
set_parameter_property HASH_LUT_MODE WIDTH ""
set_parameter_property HASH_LUT_MODE TYPE INTEGER
set_parameter_property HASH_LUT_MODE UNITS None
set_parameter_property HASH_LUT_MODE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HASH_LUT_MODE DESCRIPTION ""
set_parameter_property HASH_LUT_MODE HDL_PARAMETER true
add_parameter OUTPUT_FIFO_DEPTH INTEGER 128 ""
set_parameter_property OUTPUT_FIFO_DEPTH DEFAULT_VALUE 128
set_parameter_property OUTPUT_FIFO_DEPTH DISPLAY_NAME OUTPUT_FIFO_DEPTH
set_parameter_property OUTPUT_FIFO_DEPTH WIDTH ""
set_parameter_property OUTPUT_FIFO_DEPTH TYPE INTEGER
set_parameter_property OUTPUT_FIFO_DEPTH UNITS None
set_parameter_property OUTPUT_FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OUTPUT_FIFO_DEPTH DESCRIPTION ""
set_parameter_property OUTPUT_FIFO_DEPTH HDL_PARAMETER true
add_parameter BYTE_W INTEGER 8 ""
set_parameter_property BYTE_W DEFAULT_VALUE 8
set_parameter_property BYTE_W DISPLAY_NAME BYTE_W
set_parameter_property BYTE_W WIDTH ""
set_parameter_property BYTE_W TYPE INTEGER
set_parameter_property BYTE_W ENABLED false
set_parameter_property BYTE_W UNITS None
set_parameter_property BYTE_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTE_W DESCRIPTION ""
set_parameter_property BYTE_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point amm_slave_csr
# 
add_interface amm_slave_csr avalon end
set_interface_property amm_slave_csr addressUnits WORDS
set_interface_property amm_slave_csr associatedClock main_clock_sink
set_interface_property amm_slave_csr associatedReset main_reset_sink
set_interface_property amm_slave_csr bitsPerSymbol 8
set_interface_property amm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property amm_slave_csr burstcountUnits WORDS
set_interface_property amm_slave_csr explicitAddressSpan 0
set_interface_property amm_slave_csr holdTime 0
set_interface_property amm_slave_csr linewrapBursts false
set_interface_property amm_slave_csr maximumPendingReadTransactions 0
set_interface_property amm_slave_csr maximumPendingWriteTransactions 0
set_interface_property amm_slave_csr readLatency 0
set_interface_property amm_slave_csr readWaitTime 1
set_interface_property amm_slave_csr setupTime 0
set_interface_property amm_slave_csr timingUnits Cycles
set_interface_property amm_slave_csr writeWaitTime 0
set_interface_property amm_slave_csr ENABLED true
set_interface_property amm_slave_csr EXPORT_OF ""
set_interface_property amm_slave_csr PORT_NAME_MAP ""
set_interface_property amm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property amm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port amm_slave_csr amm_slave_csr_address_i address Input AMM_CSR_ADDR_W
add_interface_port amm_slave_csr amm_slave_csr_read_i read Input 1
add_interface_port amm_slave_csr amm_slave_csr_readdata_o readdata Output AMM_CSR_DATA_W
add_interface_port amm_slave_csr amm_slave_csr_write_i write Input 1
add_interface_port amm_slave_csr amm_slave_csr_writedata_i writedata Input AMM_CSR_DATA_W
set_interface_assignment amm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point amm_slave_lut
# 
add_interface amm_slave_lut avalon end
set_interface_property amm_slave_lut addressUnits WORDS
set_interface_property amm_slave_lut associatedClock main_clock_sink
set_interface_property amm_slave_lut associatedReset main_reset_sink
set_interface_property amm_slave_lut bitsPerSymbol 8
set_interface_property amm_slave_lut burstOnBurstBoundariesOnly false
set_interface_property amm_slave_lut burstcountUnits WORDS
set_interface_property amm_slave_lut explicitAddressSpan 0
set_interface_property amm_slave_lut holdTime 0
set_interface_property amm_slave_lut linewrapBursts false
set_interface_property amm_slave_lut maximumPendingReadTransactions 0
set_interface_property amm_slave_lut maximumPendingWriteTransactions 0
set_interface_property amm_slave_lut readLatency 0
set_interface_property amm_slave_lut readWaitTime 1
set_interface_property amm_slave_lut setupTime 0
set_interface_property amm_slave_lut timingUnits Cycles
set_interface_property amm_slave_lut writeWaitTime 0
set_interface_property amm_slave_lut ENABLED true
set_interface_property amm_slave_lut EXPORT_OF ""
set_interface_property amm_slave_lut PORT_NAME_MAP ""
set_interface_property amm_slave_lut CMSIS_SVD_VARIABLES ""
set_interface_property amm_slave_lut SVD_ADDRESS_GROUP ""

add_interface_port amm_slave_lut amm_slave_lut_address_i address Input AMM_LUT_ADDR_W
add_interface_port amm_slave_lut amm_slave_lut_write_i write Input 1
add_interface_port amm_slave_lut amm_slave_lut_writedata_i writedata Input AMM_LUT_DATA_W
set_interface_assignment amm_slave_lut embeddedsw.configuration.isFlash 0
set_interface_assignment amm_slave_lut embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment amm_slave_lut embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment amm_slave_lut embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ast_source
# 
add_interface ast_source avalon_streaming start
set_interface_property ast_source associatedClock main_clock_sink
set_interface_property ast_source associatedReset main_reset_sink
set_interface_property ast_source dataBitsPerSymbol 8
set_interface_property ast_source errorDescriptor ""
set_interface_property ast_source firstSymbolInHighOrderBits true
set_interface_property ast_source maxChannel 0
set_interface_property ast_source readyLatency 0
set_interface_property ast_source ENABLED true
set_interface_property ast_source EXPORT_OF ""
set_interface_property ast_source PORT_NAME_MAP ""
set_interface_property ast_source CMSIS_SVD_VARIABLES ""
set_interface_property ast_source SVD_ADDRESS_GROUP ""

add_interface_port ast_source ast_source_endofpacket_o endofpacket Output 1
add_interface_port ast_source ast_source_data_o data Output AST_SOURCE_SYMBOLS*BYTE_W
add_interface_port ast_source ast_source_empty_o empty Output 1
add_interface_port ast_source ast_source_ready_i ready Input 1
add_interface_port ast_source ast_source_startofpacket_o startofpacket Output 1
add_interface_port ast_source ast_source_valid_o valid Output 1


# 
# connection point main_clock_sink
# 
add_interface main_clock_sink clock end
set_interface_property main_clock_sink clockRate 0
set_interface_property main_clock_sink ENABLED true
set_interface_property main_clock_sink EXPORT_OF ""
set_interface_property main_clock_sink PORT_NAME_MAP ""
set_interface_property main_clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property main_clock_sink SVD_ADDRESS_GROUP ""

add_interface_port main_clock_sink main_clk_i clk Input 1


# 
# connection point src_clock_sink
# 
add_interface src_clock_sink clock end
set_interface_property src_clock_sink clockRate 0
set_interface_property src_clock_sink ENABLED true
set_interface_property src_clock_sink EXPORT_OF ""
set_interface_property src_clock_sink PORT_NAME_MAP ""
set_interface_property src_clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property src_clock_sink SVD_ADDRESS_GROUP ""

add_interface_port src_clock_sink ast_source_clk_i clk Input 1


# 
# connection point main_reset_sink
# 
add_interface main_reset_sink reset end
set_interface_property main_reset_sink associatedClock main_clock_sink
set_interface_property main_reset_sink synchronousEdges DEASSERT
set_interface_property main_reset_sink ENABLED true
set_interface_property main_reset_sink EXPORT_OF ""
set_interface_property main_reset_sink PORT_NAME_MAP ""
set_interface_property main_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property main_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port main_reset_sink main_srst_i reset Input 1


# 
# connection point src_reset_sink
# 
add_interface src_reset_sink reset end
set_interface_property src_reset_sink associatedClock main_clock_sink
set_interface_property src_reset_sink synchronousEdges DEASSERT
set_interface_property src_reset_sink ENABLED true
set_interface_property src_reset_sink EXPORT_OF ""
set_interface_property src_reset_sink PORT_NAME_MAP ""
set_interface_property src_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property src_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port src_reset_sink ast_source_srst_i reset Input 1


# 
# connection point ast_sink
# 
add_interface ast_sink avalon_streaming end
set_interface_property ast_sink associatedClock main_clock_sink
set_interface_property ast_sink associatedReset main_reset_sink
set_interface_property ast_sink dataBitsPerSymbol 8
set_interface_property ast_sink errorDescriptor ""
set_interface_property ast_sink firstSymbolInHighOrderBits true
set_interface_property ast_sink maxChannel 0
set_interface_property ast_sink readyLatency 0
set_interface_property ast_sink ENABLED true
set_interface_property ast_sink EXPORT_OF ""
set_interface_property ast_sink PORT_NAME_MAP ""
set_interface_property ast_sink CMSIS_SVD_VARIABLES ""
set_interface_property ast_sink SVD_ADDRESS_GROUP ""

add_interface_port ast_sink ast_sink_ready_o ready Output 1
add_interface_port ast_sink ast_sink_valid_i valid Input 1
add_interface_port ast_sink ast_sink_empty_i empty Input 3
add_interface_port ast_sink ast_sink_endofpacket_i endofpacket Input 1
add_interface_port ast_sink ast_sink_startofpacket_i startofpacket Input 1
add_interface_port ast_sink ast_sink_data_i data Input AST_SINK_SYMBOLS*BYTE_W

